In [2]:
import torch
x = torch.tensor([[1,2,3], [4,5,6]])
y = torch.tensor([[7,8,9], [10,11,12]])

f = 2*x + y
print(f)

tensor([[ 9, 12, 15],
        [18, 21, 24]])


Tensors function similar to numpy arrays. Note that operations happen element-wise for addition.

In [3]:
shape = [2,3]
xzeros = torch.zeros(shape)
xones = torch.ones(shape)
xrnd = torch.rand(shape)

print(xzeros)
print(xones)
print(xrnd)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7344, 0.8786, 0.9898],
        [0.4231, 0.9634, 0.6630]])


We have certain pre-defined functions to generate us tensors for a specified shape.

In [4]:
torch.manual_seed(42)
print(torch.rand(shape))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


## Converting between numpy and tensors

In [9]:
import numpy as np

xnp = np.array([[1,2,3],[4,5,6]]).astype("int64")

f2 = torch.from_numpy(xnp) + y

print(f2)
print(f2.type())

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.LongTensor


Note that this can be finicky about what type of data type you have in numpy in terms of going to tensors. Know your data types and this becomes an easy conversion.

In [10]:
print(x[0])
print(x[1][0:2])

tensor([1, 2, 3])
tensor([4, 5])


In [11]:
print(x.view(-1))
print(x.view(3,2))
print(x.view(6,1))

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [12]:
print(x.view(3,-1))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [13]:
print(x.transpose(0,1))

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [15]:
# if needed to swap axes...

a = torch.ones(1,2,3,4)
print(a.transpose(0,3).transpose(1,2).size())
print(a.permute(3,2,1,0).size())

torch.Size([4, 3, 2, 1])
torch.Size([4, 3, 2, 1])


Note that all of these are assignment operations... this will make a new object and not change the existing object. Most functions that will replace the value with the transformation have a trailing underscore.

In [18]:
print(x)
x.transpose_(1,0)
print(x)


print(y)
y.add_(x*2)
print(y)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 9, 12, 15],
        [18, 21, 24]])
